apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    url: ${INFLUXDB_URL}
    access: proxy
    isDefault: true
    jsonData:
      dbName: ${INFLUXDB_BUCKET}
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token ${INFLUXDB_TOKEN}'
