# Node-RED Dockerfile
FROM nodered/node-red

# Install Node-RED InfluxDB integration
RUN npm install \
  node-red-contrib-influxdb \
  node-red-contrib-sun-position \
  node-red-contrib-cron-plus \
  node-red-contrib-nmap

